#tools
[submodule "bashscripts"]
	path = bashscripts
	url = git@github.com:aurmich/bashscripts_fila5.git

#Modules
[submodule "laravel/Modules/Activity"]
	path = laravel/Modules/Activity
	url = git@github.com:aurmich/module_activity_fila5.git
[submodule "laravel/Modules/Chart"]
	path = laravel/Modules/Chart
	url = git@github.com:aurmich/module_chart_fila5.git
[submodule "laravel/Modules/CloudStorage"]
	path = laravel/Modules/CloudStorage
	url = git@github.com:healthcare_app-tv/module_cloudstorage_fila5.git
[submodule "laravel/Modules/Gdpr"]
	path = laravel/Modules/Gdpr
	url = git@github.com:aurmich/module_gdpr_fila5.git
[submodule "laravel/Modules/healthcare_app"]
	path = laravel/Modules/healthcare_app
	url = git@github.com:aurmich/module_healthcare_app_fila5.git
[submodule "laravel/Modules/Xot"]
	path = laravel/Modules/Xot
	url = git@github.com:aurmich/module_xot_fila5.git
[submodule "laravel/Modules/Limesurvey"]
	path = laravel/Modules/Limesurvey
	url = git@github.com:aurmich/module_limesurvey_fila5.git
[submodule "laravel/Modules/User"]
	path = laravel/Modules/User
	url = git@github.com:aurmich/module_user_fila5.git
[submodule "laravel/Modules/Notify"]
	path = laravel/Modules/Notify
	url = git@github.com:aurmich/module_notify_fila5.git
[submodule "laravel/Modules/UI"]
	path = laravel/Modules/UI
	url = git@github.com:aurmich/module_ui_fila5.git
[submodule "laravel/Modules/Lang"]
	path = laravel/Modules/Lang
	url = git@github.com:healthcare_app-tv/module_lang_fila5.git
[submodule "laravel/Modules/Job"]
	path = laravel/Modules/Job
	url = git@github.com:aurmich/module_job_fila5.git
[submodule "laravel/Modules/Media"]
	path = laravel/Modules/Media
	url = git@github.com:aurmich/module_media_fila5.git
[submodule "laravel/Modules/Tenant"]
	path = laravel/Modules/Tenant
	url = git@github.com:aurmich/module_tenant_fila5.git

#Themes
[submodule "laravel/Themes/Zero"]
	path = laravel/Themes/Zero
	url = git@github.com:aurmich/theme_zero_fila5.git


#packages

#docs


#to order !

